export const FIND_FRIEND_REQUEST = "FIND_FRIEND_REQUEST";
export const FIND_FRIEND_SUCCESS = "FIND_FRIEND_SUCCESS";
export const FIND_FRIEND_FAIL = "FIND_FRIEND_REQUEST";


export const MY_FRIEND_REQUEST = 'MY_FRIEND_REQUEST'
export const MY_FRIEND_SUCCESS = 'MY_FRIEND_SUCCESS'
export const MY_FRIEND_FAIL = 'MY_FRIEND_FAIL'
