export const SEND_FRIEND_REQUEST_REQUEST = "SEND_FRIEND_REQUEST_REQUSET";
export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS";
export const SEND_FRIEND_REQUEST_FAIL = "SEND_FRIEND_REQUEST_FAIL";

export const CANCEL_FRIEND_REQUEST_REQUEST = "CANCEL_FRIEND_REQUEST_REQUSET";
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS";
export const CANCEL_FRIEND_REQUEST_FAIL = "CANCEL_FRIEND_REQUEST_FAIL";

export const CONFIRM_FRIEND_REQUEST = "CONFIRM_FRIEND_REQUSET";
export const CONFIRM_FRIEND_SUCCESS = "CONFIRM_FRIEND_SUCCESS";
export const CONFIRM_FRIEND_FAIL = "CONFIRM_FRIEND_FAIL";

export const DELETE_FRIEND_REQUEST = "DELETE_FRIEND_REQUSET";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAIL = "DELETE_FRIEND_FAIL";

export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL";

export const REMOVE_USER = "REMOVE_USER";
