export const POST_SUBMISSION_REQUEST = 'POST_SUBMISSION_REQUEST';
export const POST_SUBMISSION_SUCCESS = 'POST_SUBMISSION_SUCCESS';
export const POST_SUBMISSION_FAIL = 'POST_SUBMISSION_REQUEST';



export const POST_GET_REQUEST = 'POST_GET_REQUEST';
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';
export const POST_GET_FAIL = 'POST_GET_REQUEST';



export const POST_SUBMISSON_DATA_RECEIVED = 'POST_SUBMISSON_DATA_RECEIVED'